#!/bin/bash
source "$(dirname "$0")/helpers"

step "4/6" "Installing Arch base system (pacstrap)..."

pacstrap -K /mnt \
  base base-devel linux linux-firmware \
  networkmanager grub efibootmgr \
  git curl wget sudo zsh \
  nano vim || die "pacstrap failed"

ok "Base system installed"

step "5/6" "Generating fstab..."
genfstab -U /mnt >> /mnt/etc/fstab
ok "fstab generated"
